### ISSUE TITLE
USER STORY: Intuitive Landing Page

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#1]
As a **first-time visitor**, I want to **know what the shop sells immediately** so that I can **decide whether I will browse further**.

## Acceptance Criteria
- A user can view bookstore-related hero image upon landing the website.
- A user can see book covers on the landing page.
- A user can add books to the basket on the landing page.

## Tasks
- [x] Add bookstore-related hero image.
- [x] Display bestselling and newly released book covers on the landing page.
- [x] Add 'Add to basket' buttons to each book.
