### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#10]
As a **site user**, I want to **have a personalised user profile** so that I can **view my loyalty points and order history**.

## Acceptance Criteria
- A logged-in user can view their profile page.
- A profile page has menus to check the user's loyalty points and order history.

## Tasks
- [x] Create a profile model.
- [x] Create a template to display the profile menus.
- [x] Create a view to handle the user's request.
