### ISSUE TITLE
USER STORY: Sorting All Books

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#13]
As a **shopper**, I want to **sort all the available books by publishing date** so that I can **easily identify newly released books**.

## Acceptance Criteria
- A user can view all the books sorted by title(A to Z) by default.
- A user can sort all books by specific criteria.
- A user can view a list of books sorted by the given criteria.

## Tasks
- [x] Create a view to retrieve all the books.
- [x] Create a template to display all books.
- [x] Create a dropdown menu to change sort criteria.
- [x] Create a function to handle the sort request.
