### ISSUE TITLE
USER STORY: Category-Specific Sorting

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#14]
As a **shopper**, I want to **sort sci-fi books by user ratings** so that I can **easily identify the best rated books in sci-fi**.

## Acceptance Criteria
- A user can view a list of categorised books.
- A user can sort books in a specific category by specific criteria.
- A user can view a list of books sorted by the given criteria.

## Tasks
- [x] Create a view to retrieve books by category.
- [x] Create a template to display a list of books.
- [x] Create a dropdown menu to change sort criteria.
- [x] Add a rating option to the select dropdown menu.
- [x] Add a function to handle the rating option in views.py.
