### ISSUE TITLE
USER STORY: Searching

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#15]
As a **shopper**, I want to **search for a book by title** so that I can **easily find a book I’d like to purchase**.

## Acceptance Criteria
- A user can view a search box in the header.
- A user can input a keyword in the search box.
- A user can view the result of their search keyword.

## Tasks
- [x] Create a search box in the header.
- [x] Create a view to return search results.
- [x] Create a template for the search results.
