### ISSUE TITLE
USER STORY: Read Reviews

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#16]
As a **shopper**, I want to **view reviews of a book** so that I can **check what other people think of it**.

## Acceptance Criteria
- A user can read reviews for each book without signing in.
- A review displays a reviewer's username, review and the time they posted.

## Tasks
- [x] Add a review section to the book detail page.
- [x] Create a template for the large number of reviews.
- [x] Create a view to render a review page.
