### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#2]
As a **first-time visitor**, I want to **navigate pages easily** so that I can **find information I’m looking for**.

## Acceptance Criteria
- A user can find a navigation bar in the header.
- A user can find the privacy policy, T&C and help centre in the footer.
- Each link/button is linked to the corresponding page.

## Tasks
- [x] Create a header with a navigation bar.
- [x] Create the privacy policy, T&C and help centre in the footer
- [x] Add href attributes to a tags correctly.
