### ISSUE TITLE
USER STORY: Delete Reviews

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#20]
As a **shopper**, I want to **remove my review** so that I can **delete an invalid or irrelevant review**.

## Acceptance Criteria
- A user can see a delete button to their own review on the book detail page.
- A user can delete their review by clicking the button.
- A user needs to confirm their action.

## Tasks
- [x] Add a delete button to the detail page review section.
- [x] Create a template to get the user's confirmation.
- [x] Create a view to handle request.
