### ISSUE TITLE
USER STORY: View Basket

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#22]
As a **shopper**, I want to **view items in my basket to be purchased** so that I can **identify the total cost of my purchase and all items I will receive**.

## Acceptance Criteria
- A user can see the basket button in the navigation bar.
- A user can go to the basket page by clicking the button.
- A user can view the items in the basket and the details.
- A user can see the total cost to be paid on the basket page.

## Tasks
- [x] Link the navigation menu item to the basket page.
- [x] Create a template to display the items.
- [x] Create a function to pass the context of the basket.
