### ISSUE TITLE
USER STORY: Input Payment Information

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#24]
As a **shopper**, I want to **easily enter my payment information** so that I can **check out quickly and with little hassle**.

## Acceptance Criteria
- A user can easily open the payment page from anywhere on the site.
- A user can see the payment info that they have entered.
- A user gets feedback for their input.

## Tasks
- [x] Set up Stripe.
- [x] Style the payment page.
- [x] Confirm feedback messages.
