### ISSUE TITLE
USER STORY: Loyalty Points

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#25]
As a **shopper**, I want to **collect loyalty points** so that I can **use it to purchase books**.

## Acceptance Criteria
- A user can see how many points they will get when purchasing.
- A user can see their loyalty points on profile page.
- A user can use their loyalty points buying books.

## Tasks
- [x] Add a section to display the collectable points on checkout page.
- [x] Create a profile template and add the points section.
- [x] Add a form to apply the points redemption.
