### ISSUE TITLE
USER STORY: Order Confirmation Page

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#27]
As a **shopper**, I want to **view an order confirmation after checkout** so that I can **verify that I haven't made any mistakes**.

## Acceptance Criteria
- A user can see the confirmation page as soon as they make purchases.
- A user can see the details of their order.

## Tasks
- [x] Create a view to handle get request.
- [x] Create a template to display the user's order.
- [x] Create a url path.
