### ISSUE TITLE
USER STORY: Invoice Email

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#28]
As a **shopper**, I want to **receive an email confirmation after checking out** so that I can **keep it as an invoice of what I've purchased for my records**.

## Acceptance Criteria
- A shopper receives a confirmation email when they make a purchase.
- A email contains the order details including items and total price and delivery information.
- A shopper can be a signed-in user or anonymous one.

## Tasks
- [x] Write email heading and body containing order details and delivery information.
- [x] Create a function to handle sending a confirmation email.
- [x] Set up email smtp and other env variables.
