### ISSUE TITLE
USER STORY: Trustworthy Site

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#3]
As a **shopper**, I want to **know if the shop is trustworthy** so that I can **make a purchase without any worry**.

## Acceptance Criteria
- A user can view the privacy policy and T&C.
- A user can visit the social media page by clicking the link from the site.
- A user can contact the store.

## Tasks
- [x] Create the privacy policy and T&C page.
- [x] Create the social media page and add link.
- [x] Create contact us page.
