### ISSUE TITLE
USER STORY: Contact Store

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#30]
As a **shopper**, I want to **contact the store** so that I can **receive answers to my queries before purchase**.

## Acceptance Criteria
- A user can easily see how to contact the store.
- A user can contact the store by filling in the form.
- A user gets the confirmation feedback.

## Tasks
- [x] Create a form to get a user's contact.
- [x] Set up smtp.
- [x] Add feedback messages.
