### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#35]
As a **store owner**, I want to **delete a product** so that I can **remove items that are no longer for sale**.

## Acceptance Criteria
- Only an authorised user can delete an item.
- A user needs to confirm their action.
- A user gets feedback on whether it's successful.

## Tasks
- [x] Create a button to render the deletion confirmation page.
- [x] Create a template to confirm the superuser's action.
- [x] Create a view to handle the deletion.
