### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#4]
As a **site user**, I want to **sign up** so that I can **save and view my details**.

## Acceptance Criteria
- A user can view a registration form by clicking a registration button.
- A user can create an account by filling in the form.
- A user can confirm their registration via email.

## Tasks
- [x] Create a registration button.
- [x] Import django-allauth package and templates.
- [x] Style the templates.
- [x] Set up smtp settings.
