### ISSUE TITLE
USER STORY: View List of Books

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#46]
As a **shopper**, I want to **view a list of all books** so that I can **easily select some to purchase**.

## Acceptance Criteria
- A user can view a list of books.
- A user can see necessary information.
- A user can add books to basket.

## Tasks
- [x] Create a template to display a list of books.
- [x] Create views to get the book data.
- [x] Add the add to basket button to each book.
