### ISSUE TITLE
USER STORY: View List of Deals, Bestsellers and New Releases

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#47]
As a **shopper**, I want to **quickly identify deals, bestsellers and new releases** so that I can **easily find interesting books**.

## Acceptance Criteria
- A user can see menu items or buttons to go to the deals, bestsellers and new releases pages.
- A user can view a list of deals, bestsellers and new releases.

## Tasks
- [x] Create menu/button for the deals, bestsellers and new releases pages.
- [x] Create a template to display a list of specified books.
- [x] Create  views to get specified data.
