### ISSUE TITLE
USER STORY: View Details

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#48]
As a **shopper**, I want to **view individual book details** so that I can **decide whether I want to buy the book**.

## Acceptance Criteria
- A user can view details of a book by clicking a button from the list page.
- A user can add a book to the basket.
- A superuser can edit/delete a book from the details page.

## Tasks
- [x] Create a template to display book details.
- [x] Create a url path.
- [x] Create a view to handle the request.
