### ISSUE TITLE
USER STORY: Sign In & Sign Out

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#5]
As a **site user**, I want to **sign in and sign out of my account with my credentials** so that I can **keep my account secure**.

## Acceptance Criteria
- A user can view sign in form by clicking the sign in button.
- A user can sign in by fill in the sign in form with their email and password.
- A user can sign out by clicking the sign out button.

## Tasks
- [x] Create a sign in & sign out button.
- [x] Style the sign in page.
- [x] Modify allauth templates.
