### ISSUE TITLE
USER STORY: Password Change

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#6]
As a **site user**, I want to **update my password** so that I can **keep my account secure**.

## Acceptance Criteria
- A user can view a password change form.
- A user can change their password by filling in the password change form.
- A user can confirm their password has been changed successfully from the alert message.

## Tasks
- [x] Create a button to open the password change page.
- [x] Modify allauth template.
- [x] Set up django messages.
