### ISSUE TITLE
USER STORY: Password Reset

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#7]
As a **site user**, I want to **reset my password** so that I can **access my account even if I forget my password**.

## Acceptance Criteria
- A user can see a 'forgot password?' button on the sign in page.
- A user can view the password reset form by clicking the 'forgot password?' button.
- A user can reset their password by confirming their email.

## Tasks
- [x] Create a 'forgot password?' button on the sign in page.
- [x] Modify and style allauth templates.
- [x] Set up smtp settings.
