### ISSUE TITLE
USER STORY: User Profile - Save Delivery Information

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/cogito-books#8]
As a **site user**, I want to **save my delivery information** so that I **don’t have to fill in the form every time I make a purchase**.

## Acceptance Criteria
- A user can view the delivery information form on the profile page.
- A user can save their delivery information on the profile page.
- A user can save their delivery information when they make a purchase by checking a checkbox.

## Tasks
- [x] Create a delivery information form on the profile page.
- [x] Create a view to save the shopper's delivery information by checking a checkbox on the checkout page.
- [x] Style the delivery information form.
